// This root deliberately takes almost nothing. Lab settings, project ids and
// generated secrets are read from the bootstrap root's state; only the values
// that provider configuration depends on are variables, because Terraform
// forbids a provider from depending on remote state or on a resource.
//
// build/users.auto.tfvars.json is shared with the bootstrap root, so both see
// the same parsed CSV and cannot disagree about who exists.

variable "developers" {
  description = "Developer environments, keyed by slug. Generated by lib/parse_users.py."
  type = map(object({
    first_name      = string
    last_name       = string
    display_name    = string
    username        = string
    role            = string
    vnet_cidr       = string
    subnet_app_cidr = string
    network_index   = number
  }))

  validation {
    condition     = length(var.developers) <= 3
    error_message = "This root declares 3 provider aliases. Add another provider and module block in main.tf before adding a fourth OpenStack developer."
  }

  validation {
    condition     = length(var.developers) >= 2
    error_message = "The brief requires at least 2 developers; add rows to the CSV."
  }
}

// Declared only so the shared tfvars file has no undeclared variables. Leads
// hold Keystone roles, which the bootstrap root grants; they own no data-plane
// resource of their own.
variable "leads" {
  description = "DevOps leads, keyed by slug. Generated by lib/parse_users.py."
  type = map(object({
    first_name   = string
    last_name    = string
    display_name = string
    username     = string
    role         = string
  }))
  default = {}
}

variable "project_name" {
  description = "Must match the bootstrap root; forms the project names the providers authenticate to"
  type        = string
  default     = "techsprint"
}

variable "environment_short" {
  description = "Must match the bootstrap root"
  type        = string
  default     = "test"
}

variable "identity_domain_name" {
  description = "Keystone domain that owns the TechSprint projects"
  type        = string
  default     = "TechSprint"
}

variable "object_auth_url" {
  description = <<-EOT
    Keystone endpoint written into the guest rclone configuration. deploy.sh
    passes the value of OS_AUTH_URL, so it always matches the cloud Terraform
    itself authenticated to.
  EOT
  type        = string
}
