// Inputs for the Azure stack. `developers` and `leads` come from
// build/users.auto.tfvars.json, which lib/parse_users.py writes from the CSV;
// everything else has a default matching the assignment's requirements.

variable "subscription_id" {
  description = "Azure for Students subscription id (az account show --query id -o tsv)"
  type        = string

  validation {
    condition     = can(regex("^[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$", var.subscription_id))
    error_message = "subscription_id must be a GUID."
  }
}

variable "tenant_id" {
  description = "Entra ID tenant id (az account show --query tenantId -o tsv)"
  type        = string
}

// --- project identity --------------------------------------------------------

variable "project_name" {
  description = "Value of the mandatory 'project' tag and the name prefix"
  type        = string
  default     = "techsprint"
}

variable "environment" {
  description = "Value of the mandatory 'environment' tag"
  type        = string
  default     = "testing"
}

variable "environment_short" {
  description = "Abbreviated environment for resource names, so they stay inside length limits"
  type        = string
  default     = "test"
}

// --- users, from the CSV -----------------------------------------------------

variable "developers" {
  description = "Developer environments, keyed by slug. Generated by lib/parse_users.py."
  type = map(object({
    first_name      = string
    last_name       = string
    display_name    = string
    username        = string
    role            = string
    vnet_cidr       = string
    subnet_app_cidr = string
    network_index   = number
  }))

  validation {
    condition     = length(var.developers) >= 2
    error_message = "The brief requires at least 2 developers; add rows to the CSV."
  }

  validation {
    // Two developers sharing an address range would silently break the network
    // isolation requirement, so fail the plan instead of the review.
    condition     = length(distinct([for dev in var.developers : dev.vnet_cidr])) == length(var.developers)
    error_message = "Every developer needs a distinct vnet_cidr; check lib/parse_users.py output."
  }
}

variable "leads" {
  description = "DevOps leads, keyed by slug. Generated by lib/parse_users.py."
  type = map(object({
    first_name   = string
    last_name    = string
    display_name = string
    username     = string
    role         = string
  }))

  validation {
    condition     = length(var.leads) >= 1
    error_message = "The brief requires a DevOps lead."
  }
}

// --- placement and compute ---------------------------------------------------

variable "hub_location" {
  description = "Policy-allowed region for the lead/jump VNet"
  type        = string
  default     = "denmarkeast"

  validation {
    condition = contains([
      "germanywestcentral",
      "denmarkeast",
      "belgiumcentral",
      "austriaeast",
      "switzerlandnorth",
    ], var.hub_location)
    error_message = "hub_location must be permitted by the Azure for Students policy."
  }
}

variable "developer_placements" {
  description = <<-EOT
    Ordered regional placements for developers. Azure for Students permits only
    six vCPUs per region, while one developer needs four. The CSV network_index
    selects an entry, so two developers can be spread across two regions while
    the deployment remains driven by one CSV.
  EOT
  type = list(object({
    location = string
    vm_size  = string
  }))
  default = [
    {
      location = "denmarkeast"
      vm_size  = "Standard_B2s"
    },
    {
      location = "austriaeast"
      vm_size  = "Standard_D2ls_v6"
    },
    {
      location = "belgiumcentral"
      vm_size  = "Standard_D2ls_v6"
    },
  ]

  validation {
    condition     = length(var.developer_placements) >= length(var.developers)
    error_message = "Provide one policy- and quota-compatible placement per developer."
  }

  validation {
    condition = alltrue([
      for placement in var.developer_placements : contains([
        "germanywestcentral",
        "denmarkeast",
        "belgiumcentral",
        "austriaeast",
        "switzerlandnorth",
      ], placement.location)
    ])
    error_message = "Every developer location must be permitted by the student subscription policy."
  }

  validation {
    condition = alltrue([
      for placement in var.developer_placements : contains([
        "Standard_B2s",
        "Standard_B2ls_v2",
        "Standard_D2ls_v6",
      ], placement.vm_size)
    ])
    error_message = "Every developer VM size must provide exactly 2 vCPU and 4 GB RAM."
  }
}

variable "lead_vm_size" {
  description = "Lead/jump VM size from a separate quota family in Denmark East"
  type        = string
  default     = "Standard_A1_v2"
}

variable "moodle_instance_count" {
  description = "Moodle application VMs per developer. The brief asks for two, to simulate HA."
  type        = number
  default     = 2

  validation {
    condition     = var.moodle_instance_count >= 2
    error_message = "The brief requires two Moodle instances behind the load balancer."
  }
}

variable "os_image" {
  description = <<-EOT
    Rocky Linux 9, as the brief allows. Requires a one-time marketplace terms
    acceptance on the subscription:
      az vm image terms accept --publisher resf --offer rockylinux-x86_64 --plan 9-base
    CentOS Stream 9 or an Azure Linux image are documented alternatives in
    docs/05-design-decisions.md.
  EOT
  type = object({
    publisher = string
    offer     = string
    sku       = string
    version   = string
  })
  default = {
    publisher = "resf"
    offer     = "rockylinux-x86_64"
    sku       = "9-base"
    version   = "latest"
  }
}

variable "os_image_requires_plan" {
  description = <<-EOT
    Marketplace images (Rocky Linux, CentOS Stream from a community publisher)
    need a plan block and a one-time terms acceptance. First-party images
    (Ubuntu, Azure Linux) reject a plan block, so set this to false if you
    switch os_image to one of those.
  EOT
  type        = bool
  default     = true
}

variable "data_disk_size_gb" {
  description = "Second managed disk per VM, mounted at /mnt/techsprint-data. The brief requires two disks."
  type        = number
  default     = 32
}

variable "admin_username" {
  description = "Linux admin user. Azure rejects a list of reserved names."
  type        = string
  default     = "techsprint"

  validation {
    condition     = !contains(["admin", "administrator", "root", "test", "user", "guest"], lower(var.admin_username))
    error_message = "That username is on Azure's reserved list."
  }
}

// --- networking --------------------------------------------------------------

variable "hub_vnet_cidr" {
  description = "Hub VNet holding the jump host and lead VM. Must not overlap any developer range."
  type        = string
  default     = "10.0.0.0/16"
}

variable "hub_subnet_cidr" {
  description = "Subnet inside the hub for the jump host"
  type        = string
  default     = "10.0.1.0/24"
}

variable "admin_source_ip" {
  description = <<-EOT
    Your own address in CIDR form. The jump host's NSG allows SSH from here
    only, so the single public entry point is not exposed to the internet.
      curl -s https://ifconfig.me
  EOT
  type        = string

  validation {
    condition     = can(regex("^([0-9]{1,3}\\.){3}[0-9]{1,3}/(3[0-2]|[12]?[0-9])$", var.admin_source_ip))
    error_message = "admin_source_ip must be CIDR, e.g. 203.0.113.45/32."
  }
}
