#!/usr/bin/env python3
"""Turn Terraform output into an Ansible inventory.

The brief says "Skripta se pokreće jednom, ne pokreće se više skripti", so no
address, key path or password may be typed by a human between the Terraform and
Ansible halves. This bridges them: it reads `terraform output -json` and writes
a complete inventory, including the ProxyCommand that routes every connection
through the bastion.

    terraform -chdir=iac/azure output -json > build/azure-output.json
    python3 lib/render_inventory.py --cloud azure \
        --terraform-output build/azure-output.json \
        --out ansible/inventory/azure.yml

Stdlib only, and it writes YAML by hand rather than importing PyYAML, so the
deployment has no pip dependency at all.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def quote(value) -> str:
    """Render any Python value as a valid YAML scalar.

    Uses json.dumps because JSON is a subset of YAML 1.2: a JSON scalar is
    always a valid YAML scalar. That matters here because the values include an
    SSH private key (embedded newlines), a storage account key (base64 with
    '+' and '=') and generated passwords (which can contain '#', ':' and quotes)
    - each of which breaks a hand-rolled quoting scheme in a different way, and
    a multi-line block scalar additionally has to track the current indent.
    Escaping newlines as \\n sidesteps indentation entirely.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(str(value))


def build_inventory(cloud: str, data: dict) -> str:
    inventory = data["inventory_data"]["value"]
    jump_host = inventory["jump_host"]
    admin_user = inventory["admin_username"]
    ssh_key = inventory["ssh_key"]
    environments = inventory["environments"]

    key_path = Path(ssh_key)
    if not key_path.is_file():
        raise ValueError(f"SSH private key not found: {key_path}")
    private_key_text = key_path.read_text(encoding="utf-8")
    if not private_key_text.strip():
        raise ValueError(f"SSH private key is empty: {key_path}")
    known_hosts = str(Path(ssh_key).parent / "known_hosts")

    lines: list[str] = []
    add = lines.append

    add("---")
    add("# GENERATED by lib/render_inventory.py from terraform output.")
    add("# Do not edit: re-run deploy.sh instead. Gitignored, because it holds")
    add("# the storage account key, the database password and the SSH key.")
    add("all:")
    add("  vars:")
    add(f"    techsprint_cloud: {quote(cloud)}")
    add(f"    ansible_user: {quote(admin_user)}")
    add(f"    ansible_ssh_private_key_file: {quote(ssh_key)}")
    add("")

    # --- the bastion ---------------------------------------------------------
    add("  children:")
    add("    jump:")
    add("      hosts:")
    add("        bastion:")
    add(f"          ansible_host: {quote(jump_host)}")
    # The bastion is the only host reached directly. Everything else proxies
    # through it, which is the whole point of the jump-host requirement.
    add(f"          techsprint_private_key: {quote(private_key_text)}")
    add("          techsprint_environments:")
    for slug, env in sorted(environments.items()):
        add(f"            {slug}:")
        add(f"              moodle_ips: {json.dumps(env['moodle_ips'])}")
    add("")

    # --- Moodle application nodes -------------------------------------------
    add("    moodle:")
    add("      vars:")
    # ProxyCommand is what lets Ansible configure hosts that have no public
    # address at all. -W forwards the connection through the bastion without
    # allocating a shell there.
    proxy = (
        f"-o ProxyCommand=\"ssh -W %h:%p -q "
        f"-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile={known_hosts} "
        f"-i {ssh_key} {admin_user}@{jump_host}\" "
        f"-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile={known_hosts}"
    )
    add(f"        ansible_ssh_common_args: {quote(proxy)}")
    add("      hosts:")

    for slug, env in sorted(environments.items()):
        ips = env["moodle_ips"]
        primary_host = f"{slug}-moodle-1"
        lb_address = env["load_balancer"]
        for index, ip in enumerate(ips, start=1):
            host = f"{slug}-moodle-{index}"
            add(f"        {host}:")
            add(f"          ansible_host: {quote(ip)}")
            add(f"          env_slug: {quote(slug)}")
            add(f"          env_owner_name: {quote(env['display_name'])}")
            # Node 1 owns the database; node 2 connects to it. Decided here so
            # the roles need no conditionals of their own.
            add(f"          is_db_primary: {quote(index == 1)}")
            add(f"          primary_node: {quote(primary_host)}")
            add(f"          moodle_db_host: {quote(ips[0])}")
            add(f"          moodle_db_password: {quote(env['database_password'])}")
            add(f"          moodle_admin_password: {quote(env['moodle_admin_password'])}")
            # Moodle must generate URLs for the balancer, not for itself, or
            # every link a user follows lands on a private address.
            add(f"          moodle_wwwroot: {quote('http://' + lb_address)}")
            add(f"          app_subnet_cidr: {quote(env['subnet_cidr'])}")

            if cloud == "azure":
                add(f"          azure_blob_storage_account: {quote(env['blob_storage_account'])}")
                add(f"          azure_file_storage_account: {quote(env['file_storage_account'])}")
                add(f"          azure_file_storage_key: {quote(env['file_storage_key'])}")
                add(f"          azure_blob_container: {quote(env['blob_container'])}")
                add(f"          azure_file_share: {quote(env['file_share'])}")
                add(f"          azure_identity_client_id: {quote(env['identity_client_id'])}")
            else:
                add(f"          openstack_object_container: {quote(env['object_container'])}")
                add(f"          openstack_object_auth_url: {quote(env['object_auth_url'])}")
                add(f"          openstack_object_username: {quote(env['object_username'])}")
                add(f"          openstack_object_password: {quote(env['object_password'])}")
                add(f"          openstack_object_project_name: {quote(env['project_name'])}")
                add(f"          openstack_object_domain_name: {quote(env['identity_domain'])}")
                add(f"          openstack_file_share_export: {quote(env['file_share_export'])}")
                add(f"          openstack_file_share_user: {quote(env['file_share_user'])}")
                add(f"          openstack_file_share_key: {quote(env['file_share_key'])}")
    add("")

    # Single trailing newline, no blank line at EOF.
    return "\n".join(line.rstrip() for line in lines).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--cloud", required=True, choices=["azure", "openstack"])
    parser.add_argument("--terraform-output", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    if not args.terraform_output.is_file():
        raise SystemExit(f"terraform output not found: {args.terraform_output}")

    data = json.loads(args.terraform_output.read_text(encoding="utf-8"))
    if "inventory_data" not in data:
        raise SystemExit(
            "terraform output has no 'inventory_data'. Did apply finish?\n"
            f"  keys present: {sorted(data.keys())}"
        )

    try:
        inventory = build_inventory(args.cloud, data)
    except (KeyError, ValueError) as exc:
        raise SystemExit(f"invalid Terraform output: {exc}") from exc

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(inventory, encoding="utf-8")
    # 0600: this file contains the storage key and the database password.
    args.out.chmod(0o600)
    print(f"wrote {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
