// Inputs for the OpenStack stack. Authentication comes from the OS_*
// environment variables your RC file exports, so there is nothing to put here
// for credentials. Everything else is lab-specific: the names below are
// placeholders and MUST be replaced with values from your own lab, which
// `make openstack-discover` prints for you.

// --- users, from the CSV -----------------------------------------------------

variable "developers" {
  description = "Developer environments, keyed by slug. Generated by lib/parse_users.py."
  type = map(object({
    first_name      = string
    last_name       = string
    display_name    = string
    username        = string
    role            = string
    vnet_cidr       = string
    subnet_app_cidr = string
    network_index   = number
  }))

  validation {
    condition     = length(var.developers) >= 2
    error_message = "The brief requires at least 2 developers; add rows to the CSV."
  }
}

variable "leads" {
  description = "DevOps leads, keyed by slug. Generated by lib/parse_users.py."
  type = map(object({
    first_name   = string
    last_name    = string
    display_name = string
    username     = string
    role         = string
  }))

  validation {
    condition     = length(var.leads) >= 1
    error_message = "The brief requires a DevOps lead."
  }
}

// --- project identity --------------------------------------------------------

variable "identity_domain_name" {
  description = "Dedicated SQL-backed Keystone domain created for CSV identities"
  type        = string
  default     = "TechSprint"
}

variable "project_name" {
  description = "Value of the mandatory 'project' tag"
  type        = string
  default     = "techsprint"
}

variable "environment" {
  description = "Value of the mandatory 'environment' tag"
  type        = string
  default     = "testing"
}

variable "environment_short" {
  type    = string
  default = "test"
}

// --- lab-specific identifiers -----------------------------------------------
//
// Every value in this block differs per OpenStack installation. Discover yours
// with `make openstack-discover`, which runs the openstack CLI queries in
// docs/troubleshooting.md#openstack-lab-discovery.

variable "external_network_id" {
  description = <<-EOT
    Provider network that owns floating IPs.
      openstack network list --external -f value -c ID -c Name
  EOT
  type        = string

  validation {
    condition     = can(regex("^[0-9a-fA-F-]{36}$", var.external_network_id))
    error_message = "external_network_id must be a UUID from `openstack network list --external`."
  }
}

variable "external_network_name" {
  description = "Same network, by name, for the floating IP pool"
  type        = string
}

variable "storage_network_id" {
  description = "Shared provider-storage network used by native CephFS clients"
  type        = string

  validation {
    condition     = can(regex("^[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$", var.storage_network_id))
    error_message = "storage_network_id must be the provider-storage network UUID."
  }
}

variable "image_name" {
  description = <<-EOT
    Rocky Linux or CentOS Stream image, as the brief allows.
      openstack image list --status active
    If neither exists in your lab, upload one - docs/troubleshooting.md has the command.
  EOT
  type        = string
  default     = "Rocky-9-GenericCloud"
}

variable "developer_flavor_name" {
  description = "Private 2-vCPU/4096-MB flavor created by the bootstrap"
  type        = string
  default     = "techsprint.2c4r"
}

variable "jump_flavor_name" {
  description = "Bastion flavor. Only proxies SSH, so the smallest will do."
  type        = string
  default     = "m1.small"
}

variable "octavia_amphora_flavor_name" {
  description = "Existing private flavor used by Octavia Amphora instances"
  type        = string
  default     = "octavia_65"
}

// --- networking --------------------------------------------------------------

variable "mgmt_cidr" {
  description = "Management network holding the jump host"
  type        = string
  default     = "10.100.0.0/24"
}

variable "dns_nameservers" {
  description = <<-EOT
    Resolvers for tenant subnets. Without these, cloud-init stalls for minutes
    trying to reach package mirrors. Use the lab's internal resolver if it has
    one.
  EOT
  type        = list(string)
  default     = ["8.8.8.8", "1.1.1.1"]
}

variable "admin_source_ip" {
  description = "Your address in CIDR form; the only source allowed to SSH to the bastion"
  type        = string

  validation {
    condition     = can(regex("^([0-9]{1,3}\\.){3}[0-9]{1,3}/(3[0-2]|[12]?[0-9])$", var.admin_source_ip))
    error_message = "admin_source_ip must be CIDR, e.g. 203.0.113.45/32."
  }
}

// --- compute and storage -----------------------------------------------------

variable "moodle_instance_count" {
  description = "Moodle instances per developer. Two, to simulate HA."
  type        = number
  default     = 2

  validation {
    condition     = var.moodle_instance_count >= 2
    error_message = "The brief requires two Moodle instances behind the load balancer."
  }
}

variable "data_disk_size_gb" {
  description = "Cinder data volume per instance, mounted at /var/moodledata"
  type        = number
  default     = 32
}

variable "file_share_size_gb" {
  description = "Manila CephFS backup share size per developer"
  type        = number
  default     = 5
}

variable "manila_share_type" {
  description = "Private CephFS share type prepared by deploy.sh"
  type        = string
  default     = "techsprint-cephfs"
}

variable "admin_username" {
  description = <<-EOT
    Login user baked into the cloud image. Rocky and CentOS images use
    cloud-user (older ones: rocky, centos); Ubuntu uses ubuntu. A wrong value
    here surfaces as "Permission denied (publickey)" on a correct deployment.
  EOT
  type        = string
  default     = "cloud-user"
}
